# Site settings
title: twocentstudios
email: chris@twocentstudios.com
description: > # this means to ignore newlines until "baseurl:"
  A coding blog covering iOS, Swift, and other programming topics.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://twocentstudios.com" # the base hostname & protocol for your site
twitter_username: twocentstudios
github_username:  twocentstudios
google_analytics_tracking_id: UA-10207350-1
timezone: America/Chicago
encoding: utf-8
exclude: [ deploy.sh, new.sh, Gemfile, Gemfile.lock, _design, _legacy ]
keep_files: [ .nojekyll, .git ]

# Build settings
permalink: /:year/:month/:day/:title
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
